name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  queue: max

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  deploy:
    name: Deploy
    needs:
      - ci
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        environment:
          - production
    with:
      environment: ${{ matrix.environment }}
